### PR TITLE
INFRA-176: Add sonar-project.properties - cfg file for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-plugin-examples-gate-PR27

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-plugin-examples-sonarqube-scan-zuul-gate/25/ : SUCCESS in 36s
- https://checklist.intgdc.com/job/compliance/job/gooddata-plugin-examples-merge-compliance-check/26/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-plugin-examples-fossa-scanning-zuul/2/ : SUCCESS in 46s (non-voting)

**Pull request merged**
